- name: Use Node.js v10
  uses: actions/setup-node@v1
  with:
    node-version: '10.x'
    registry-url: 'https://npm.pkg.github.com/'
    scope: '@owner'
- run: npm ci
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}